name: Build Kernel
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device: [m31]
        rom: [oneui]
        ksu: ['']
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: |
          sudo apt update && sudo apt install -y build-essential bc gcc-aarch64-linux-gnu zip python3
      - name: Build Kernel
        run: |
          chmod +x build_kernel.py
          python3 build_kernel.py --${{ matrix.rom }} --target=${{ matrix.device }} ${{ matrix.ksu }}
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-M31-Final
          path: out/*.zip
